spring.application.name=Wishlist
spring.devtools.restart.trigger-file=.reloadtrigger
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.url=${local_dev_host}
spring.datasource.username=${local_dev_username}
spring.datasource.password=${local_dev_password}
